name: Node.js CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      id: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform apply -auto-approve
        echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: Deploy Application
      env:
        PUBLIC_IP: ${{ env.PUBLIC_IP }}
      run: |
        echo "Deploying to $PUBLIC_IP"

        # Test SSH connection
        # Note: Ensure you have a valid SSH key in your local environment or that the instance has appropriate access
        ssh -o "StrictHostKeyChecking=no" ubuntu@$PUBLIC_IP 'echo "SSH connection successful"'
        
        # Deploy application
        ssh -o "StrictHostKeyChecking=no" ubuntu@$PUBLIC_IP << 'EOF'
          echo "Deploying Medusa application"
          sudo docker run -d -p 9000:9000 medusajs/medusa
        EOF
