name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      id: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform apply -auto-approve
        echo "PRIVATE_KEY=$(terraform output -raw private_key_pem)" >> $GITHUB_ENV
        echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: Deploy Application
      env:
        PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
        PUBLIC_IP: ${{ env.PUBLIC_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o "StrictHostKeyChecking=no" -i private_key.pem ubuntu@$PUBLIC_IP << EOF
          sudo docker run -d -p 9000:9000 medusajs/medusa
        EOF
